# .github/workflows/java-build-deploy.yml
name: Java Build & Deployment Example - DoX-CLI Action

on:
  workflow_call:
    inputs:
      jdk_version:
        description: 'JDK Version'
        type: string
        default: '17'

jobs:
  cicd:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: ${{ inputs.jdk_version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Maven Build
        run: |
          dox maven build

      - name: Docker Build & Push
        run: |
          dox docker build push

      - name: GitOps Deploy
        run: |
          dox gitops update-image-tag
